import React, { useEffect, useMemo, useState } from 'react';
import { ClipboardList, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { fetchAdmin, hasStoredAdminToken } from '../auth/adminAuth';
import { formatDateTime } from '../utils/formatters';
import { DetailGrid, DetailItem, InspectorDrawer, SourcePill } from './WorkspacePrimitives';

type AuditEntry = { id: string; timestamp: number | null; actorName: string; action: string; resourceType: string; resourceId: string | null; detail: string; };
function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function normalizeAuditEntry(value: unknown): AuditEntry { const row=asRecord(value); return { id:String(row.id??`${row.timestamp??'unknown'}-${row.action??'event'}-${row.resourceId??'resource'}`), timestamp:row.timestamp!==null&&row.timestamp!==undefined&&Number.isFinite(Number(row.timestamp))?Number(row.timestamp):null, actorName:String(row.actorName??'unknown'), action:String(row.action??'unknown'), resourceType:String(row.resourceType??'resource'), resourceId:row.resourceId==null?null:String(row.resourceId), detail:String(row.detail??'No detail recorded') }; }
function detailRecord(detail: string): Record<string, unknown> { try { const parsed=JSON.parse(detail); return asRecord(parsed); } catch { return {}; } }

export const AuditLogView: React.FC = () => {
  const [entries,setEntries]=useState<AuditEntry[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState('');
  const [actionFilter,setActionFilter]=useState('all'); const [resourceFilter,setResourceFilter]=useState('all'); const [selected,setSelected]=useState<AuditEntry|null>(null);
  const fetchAudit=async()=>{setLoading(true);setError(null);try{const res=await fetchAdmin('/api/admin/audit-log?limit=250');const payload=await res.json().catch(()=>[]);if(!res.ok){const message=asRecord(payload).error?String(asRecord(payload).error):`Audit request failed with HTTP ${res.status}`;setError(message);setEntries([]);return;}setEntries(Array.isArray(payload)?payload.map(normalizeAuditEntry):[]);}catch(err){setError(err instanceof Error?err.message:'Audit request failed.');setEntries([]);}finally{setLoading(false);}};
  useEffect(()=>{void fetchAudit();},[]);
  const actions=useMemo(()=>Array.from(new Set(entries.map((entry)=>entry.action))).sort(),[entries]); const resources=useMemo(()=>Array.from(new Set(entries.map((entry)=>entry.resourceType))).sort(),[entries]);
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return entries.filter((entry)=>{if(actionFilter!=='all'&&entry.action!==actionFilter)return false;if(resourceFilter!=='all'&&entry.resourceType!==resourceFilter)return false;return !term||[entry.actorName,entry.action,entry.resourceType,entry.resourceId,entry.detail].filter(Boolean).some((value)=>String(value).toLowerCase().includes(term));});},[actionFilter,entries,resourceFilter,search]);
  const detail=selected?detailRecord(selected.detail):{}; const before=detail.before??detail.beforeJson??null; const after=detail.after??detail.afterJson??null;

  return <div className="flex flex-col gap-3 h-full w-full select-none overflow-hidden pr-1">
    <div className="card-3d-glass p-3.5 flex items-center justify-between shrink-0"><div><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-lg bg-[#0051C3]/10 text-[#0051C3] flex items-center justify-center border border-[#0051C3]/20"><ClipboardList size={14}/></div><h2 className="text-[14px] font-bold">Admin Audit Log</h2><span className="text-[10px] px-2.5 py-0.5 rounded-full bg-slate-100 text-[#475569] font-mono border border-slate-200">{entries.length} events</span></div><p className="text-[10.5px] text-[#475569] mt-1">Data source: authenticated admin action audit records. Raw secrets are not exposed.</p></div><button onClick={()=>void fetchAudit()} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[#DCEBFA] bg-white text-[#0051C3] font-semibold text-[11px]"><RefreshCw size={12} className={loading?'animate-spin':''}/>Refresh</button></div>
    <div className="card-3d-glass p-3.5 flex flex-col min-h-0 flex-1">
      <div className="flex flex-wrap items-center gap-2 shrink-0 mb-3"><div className="relative min-w-[240px] flex-1 max-w-[400px]"><Search size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search actor, resource, action, detail..." className="w-full h-[30px] pl-7 pr-2 rounded-lg border border-[#DCEBFA] bg-white text-[11px] outline-none"/></div><select aria-label="Action filter" value={actionFilter} onChange={(e)=>setActionFilter(e.target.value)} className="h-[30px] rounded-lg border border-slate-200 px-2 text-[10px]"><option value="all">Action filter: All</option>{actions.map((action)=><option key={action}>{action}</option>)}</select><select aria-label="Resource filter" value={resourceFilter} onChange={(e)=>setResourceFilter(e.target.value)} className="h-[30px] rounded-lg border border-slate-200 px-2 text-[10px]"><option value="all">Resource filter: All</option>{resources.map((resource)=><option key={resource}>{resource}</option>)}</select><div className="ml-auto flex items-center gap-1.5 text-[10px] text-[#64748B]"><ShieldCheck size={12} className={hasStoredAdminToken()?'text-emerald-600':'text-amber-600'}/>{hasStoredAdminToken()?'Admin token configured':'Admin token required'}</div></div>
      {error?<div className="mb-3 rounded-xl border border-amber-200 bg-amber-50 text-amber-800 p-3 text-[11px]">{error}. Open Settings to store an admin token or bootstrap the first admin key.</div>:null}
      <div className="flex-1 min-h-0 overflow-y-auto rounded-xl border border-[#E2E8F0] bg-white/75 divide-y divide-[#E2E8F0]">{filtered.map((entry)=><button key={entry.id} onClick={()=>setSelected(entry)} className="w-full p-3 grid grid-cols-1 md:grid-cols-[120px_110px_130px_1fr] gap-2 md:gap-3 text-[11px] text-left hover:bg-blue-50/30"><div className="font-mono text-[#64748B]">{entry.timestamp?formatDateTime(entry.timestamp):'—'}</div><div className="font-bold text-[#0F172A] truncate">{entry.actorName}</div><div className="min-w-0"><SourcePill label={entry.action} tone="blue"/><div className="mt-1 font-mono text-[9.5px] text-[#64748B] truncate">{entry.resourceType}{entry.resourceId?` · ${entry.resourceId}`:''}</div></div><div className="text-[#475569] break-words">{entry.detail}</div></button>)}{!loading&&!filtered.length?<div className="p-10 text-center text-[12px] text-[#64748B]">{entries.length===0?'No audit events available.':'No audit event matches your filters.'}</div>:null}{loading&&!entries.length?<div className="p-10 text-center text-[12px] text-[#64748B]">Loading audit log...</div>:null}</div>
    </div>
    <InspectorDrawer open={Boolean(selected)} onClose={()=>setSelected(null)} title="Audit detail" subtitle={selected?.id ? <span className="font-mono">{selected.id}</span>:undefined}>
      {selected?<div className="space-y-3"><DetailGrid><DetailItem label="Actor" value={selected.actorName}/><DetailItem label="Action" value={selected.action}/><DetailItem label="Resource" value={`${selected.resourceType}${selected.resourceId?` · ${selected.resourceId}`:''}`}/><DetailItem label="Timestamp" value={selected.timestamp?formatDateTime(selected.timestamp):'Not recorded'}/></DetailGrid><div className="grid gap-2 md:grid-cols-2"><div className="rounded-xl border border-slate-200 p-3"><strong className="text-[10px]">Before</strong><pre className="mt-2 whitespace-pre-wrap break-words text-[8.5px] text-slate-500">{before==null?'Not recorded':JSON.stringify(before,null,2)}</pre></div><div className="rounded-xl border border-slate-200 p-3"><strong className="text-[10px]">After</strong><pre className="mt-2 whitespace-pre-wrap break-words text-[8.5px] text-slate-500">{after==null?'Not recorded':JSON.stringify(after,null,2)}</pre></div></div><div className="rounded-xl border border-slate-200 p-3"><strong className="text-[10px]">Raw audit detail</strong><p className="mt-2 text-[9.5px] text-slate-500 break-words">{selected.detail}</p></div></div>:null}
    </InspectorDrawer>
  </div>;
};
