import React, { useMemo, useState } from 'react';
import { Activity, Cpu, Gauge, MemoryStick, Network, TimerReset } from 'lucide-react';
import type { DashboardData } from '../types';
import { formatLatency, formatNumber } from '../utils/formatters';
import { EmptyState, MetricTile, PageHeader, SourceBadge } from './PagePrimitives';
import { DetailGrid, DetailItem, ModalDialog, ProgressBar, SourcePill } from './WorkspacePrimitives';

function mb(value: number | null | undefined): string { return value == null ? '—' : `${value.toFixed(1)} MB`; }
function seconds(value: number | null | undefined): string { if(value==null)return '—'; if(value<60)return `${Math.round(value)}s`; if(value<3600)return `${Math.floor(value/60)}m`; return `${Math.floor(value/3600)}h ${Math.floor((value%3600)/60)}m`; }

export const MetricsView: React.FC<{ data: DashboardData }> = ({ data }) => {
  const [detailOpen,setDetailOpen]=useState(false);
  const analytics=data.analytics; const runtime=data.runtime; const series=analytics?.requestVolumeSeries??[]; const maxCount=Math.max(1,...series.map((point)=>point.count));
  const providerRows=useMemo(()=>(analytics?.byProvider??[]).filter((row)=>row.providerId&&row.count>0).sort((a,b)=>b.count-a.count),[analytics?.byProvider]);
  const hasObservedMetrics=Boolean(analytics&&((analytics.totalRequests??0)>0||series.length>0||providerRows.length>0));
  const heapPct=runtime?.available&&runtime.heapUsedMb!=null&&runtime.heapTotalMb!=null&&runtime.heapTotalMb>0?Math.min(100,(runtime.heapUsedMb/runtime.heapTotalMb)*100):null;
  const rssPct=runtime?.available&&runtime.rssMb!=null&&runtime.heapTotalMb!=null&&runtime.heapTotalMb>0?Math.min(100,(runtime.rssMb/runtime.heapTotalMb)*100):null;
  const maxProviderCost=Math.max(0,...providerRows.map((row)=>row.cost??0));

  return <div className="flex flex-col gap-3 h-full w-full overflow-y-auto pr-1">
    <PageHeader icon={Gauge} title="Metrics" badge="Observed only" description="Measured edge telemetry and Local Node runtime samples. Cloudflare production runtime values are never inferred from the local process." actions={<button onClick={()=>setDetailOpen(true)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-[10px] font-bold text-blue-700">Runtime detail</button>}/>

    <section className="grid grid-cols-2 xl:grid-cols-6 gap-2.5"><MetricTile icon={Activity} label="Observed requests" value={analytics?formatNumber(analytics.totalRequests??0):'—'} note="Data source: request telemetry"/><MetricTile icon={TimerReset} label="Average latency" value={analytics?formatLatency(analytics.avgLatencyMs??null):'—'} note="Observed request latency only"/><MetricTile icon={Network} label="Request buckets" value={analytics?String(series.length):'—'} note={`Window: ${analytics?.windowHours??'—'}h`}/><MetricTile icon={MemoryStick} label="Heap used" value={runtime?.available?mb(runtime.heapUsedMb):'—'} note="Local Node runtime"/><MetricTile icon={MemoryStick} label="RSS" value={runtime?.available?mb(runtime.rssMb):'—'} note="Local Node runtime"/><MetricTile icon={Cpu} label="Runtime uptime" value={runtime?.available?seconds(runtime.uptimeSeconds):'—'} note={runtime?.source==='node-process'?'Data source: node process':'Runtime unavailable'}/></section>

    <section className="grid grid-cols-1 xl:grid-cols-12 gap-3 flex-1 min-h-[360px]">
      <div className="xl:col-span-8 card-3d-glass p-4 min-h-[320px] flex flex-col"><div className="flex items-center justify-between gap-2 mb-3"><div><h3 className="text-[12px] font-bold text-slate-900">Observed request volume</h3><p className="text-[9.5px] text-slate-500">Data source: persisted request telemetry; each bar is an actual returned bucket.</p></div><SourceBadge>D1 / local telemetry</SourceBadge></div>{series.length?<div className="flex-1 min-h-[220px] flex flex-col"><div className="flex items-center justify-between text-[8px] text-slate-400"><span>{formatNumber(maxCount)} requests</span><span>bucket max</span></div><div className="flex-1 flex items-end gap-1 rounded-xl border border-slate-200 bg-white p-3 overflow-hidden">{series.map((point,index)=>{const height=point.count>0?Math.max(3,(point.count/maxCount)*100):1;return <div key={`${point.timestamp}-${index}`} className="flex-1 min-w-[3px] h-full flex items-end group" title={`${new Date(point.timestamp).toLocaleString()} · ${point.count} requests${point.avgLatencyMs!=null?` · ${Math.round(point.avgLatencyMs)} ms`:''}`}><div className="w-full rounded-t-sm bg-blue-500/80 group-hover:bg-blue-600" style={{height:`${height}%`}}/></div>})}</div><div className="mt-2 flex justify-between text-[8.5px] text-slate-500 font-mono"><span>{series[0]?new Date(series[0].timestamp).toLocaleString():'No data'}</span><span>{series.length} observed buckets</span><span>{series.at(-1)?new Date(series.at(-1)!.timestamp).toLocaleString():'—'}</span></div></div>:<EmptyState title="No observed metrics" detail="Request-volume metrics appear after the edge records request telemetry. An empty series is not converted into synthetic traffic."/>}</div>

      <div className="xl:col-span-4 card-3d-glass p-4 min-h-[320px] flex flex-col"><div className="flex items-center justify-between gap-2 mb-3"><div><h3 className="text-[12px] font-bold text-slate-900">Runtime memory</h3><p className="text-[9.5px] text-slate-500">Local Node process only.</p></div><SourcePill label={runtime?.available?'LOCAL RUNTIME':'UNAVAILABLE'} tone={runtime?.available?'blue':'slate'}/></div><div className="grid gap-4"><div><div className="mb-1 flex justify-between text-[9.5px]"><span>Heap usage</span><span className="font-mono">{heapPct==null?'—':`${heapPct.toFixed(0)}%`}</span></div><ProgressBar value={heapPct}/><div className="mt-1 text-[8.5px] text-slate-400">{mb(runtime?.heapUsedMb)} used of {mb(runtime?.heapTotalMb)} heap</div></div><div><div className="mb-1 flex justify-between text-[9.5px]"><span>RSS vs heap capacity</span><span className="font-mono">{rssPct==null?'—':`${rssPct.toFixed(0)}%`}</span></div><ProgressBar value={rssPct}/><div className="mt-1 text-[8.5px] text-slate-400">RSS is process resident memory and may exceed heap capacity.</div></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-[9px] text-slate-500">CPU trend is not displayed because the current runtime contract exposes cumulative CPU time, not a time-series utilization sample.</div></div></div>
    </section>

    <section className="card-3d-glass p-4"><div className="flex items-center justify-between gap-2"><div><h3 className="text-[12px] font-bold text-slate-900">Provider attribution</h3><p className="text-[9.5px] text-slate-500">Observed request count, latency, and cost when present.</p></div><SourceBadge>Observed requests</SourceBadge></div><div className="mt-3 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">{providerRows.map((row)=><div key={`${row.providerId}-${row.providerName}`} className="rounded-lg border border-slate-200 bg-white p-2.5"><div className="flex items-center justify-between gap-2"><strong className="text-[10px] text-slate-800 truncate">{row.providerName}</strong><span className="text-[9px] font-mono text-slate-500">{formatNumber(row.count)}</span></div><div className="mt-1.5 flex justify-between text-[8.8px] text-slate-500"><span>Avg latency</span><span className="font-mono">{formatLatency(row.avgLatencyMs)}</span></div><div className="mt-1 flex justify-between text-[8.8px] text-slate-500"><span>Observed cost</span><span className="font-mono">{row.cost==null?'—':`$${row.cost.toFixed(6)}`}</span></div>{row.cost!=null&&maxProviderCost>0?<div className="mt-2"><ProgressBar value={row.cost} max={maxProviderCost}/></div>:null}</div>)}{!providerRows.length?<EmptyState title="No provider attribution" detail="The current telemetry window has no request rows with an authoritative provider ID."/>:null}</div></section>

    {!hasObservedMetrics?<div className="text-[9px] text-slate-500">No observed analytics data is currently available; zeros are not substituted for unknown measurements.</div>:null}

    <ModalDialog open={detailOpen} onClose={()=>setDetailOpen(false)} title="Runtime metrics detail" description="Local Node runtime evidence only; Cloudflare Worker runtime is a separate environment." size="md"><DetailGrid><DetailItem label="Heap used" value={mb(runtime?.heapUsedMb)}/><DetailItem label="Heap total" value={mb(runtime?.heapTotalMb)}/><DetailItem label="RSS" value={mb(runtime?.rssMb)}/><DetailItem label="Uptime" value={seconds(runtime?.uptimeSeconds)}/><DetailItem label="CPU user time" value={runtime?.cpuUserMs==null?'Unknown':`${runtime.cpuUserMs.toFixed(0)} ms cumulative`}/><DetailItem label="CPU system time" value={runtime?.cpuSystemMs==null?'Unknown':`${runtime.cpuSystemMs.toFixed(0)} ms cumulative`}/></DetailGrid></ModalDialog>
  </div>;
};
