import React, { useState } from 'react';
import { CheckCircle2, CircleHelp, Cloud, Database, Globe2, Info, KeyRound, PlugZap, RefreshCw, Server, ShieldCheck, Trash2, Wrench } from 'lucide-react';
import type { DashboardData } from '../types';
import { clearStoredAdminToken, getStoredAdminToken, setStoredAdminToken } from '../auth/adminAuth';
import { BootstrapAdminCard } from './BootstrapAdminCard';
import { formatRelativeTime } from '../utils/formatters';
import { DetailGrid, DetailItem, SourcePill, WorkspaceTabs } from './WorkspacePrimitives';

function PostureRow({ label, value, detail, ok = false }: { key?: string; label: string; value: string; detail: string; ok?: boolean }) {
  return <div className="rounded-lg border border-slate-200 bg-white p-2.5 flex items-start gap-2"><span className={`mt-0.5 w-2 h-2 rounded-full ${ok ? 'bg-emerald-500' : 'bg-slate-300'}`}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="text-[10.5px] text-slate-800">{label}</strong><span className="ml-auto text-[9px] font-mono text-slate-500">{value}</span></div><p className="mt-1 text-[9.5px] leading-relaxed text-slate-500">{detail}</p></div></div>;
}

export const SettingsView: React.FC<{ data: DashboardData }> = ({ data }) => {
  const [tokenDraft, setTokenDraft] = useState(() => getStoredAdminToken());
  const [tokenSaved, setTokenSaved] = useState(false);
  const [tab, setTab] = useState('General');
  const saveToken = () => { setStoredAdminToken(tokenDraft); setTokenSaved(true); window.setTimeout(()=>setTokenSaved(false),1500); };
  const clearToken = () => { clearStoredAdminToken(); setTokenDraft(''); setTokenSaved(true); window.setTimeout(()=>setTokenSaved(false),1500); };
  const status = data.omniRouteStatus; const caps = data.capabilities; const runtime = data.runtime;
  const runtimeWarning = status?.configured && status.reachable === false ? 'OmniRoute is configured but unreachable.' : !status?.configured ? 'OmniRoute origin is not configured.' : runtime?.available === false ? 'Local Node runtime metrics are unavailable.' : null;
  const capabilityRows = [
    ['Gateway authentication', caps?.gatewayAuthentication ? 'Implemented' : 'Unknown', 'Bearer authentication is executed before upstream forwarding.'],
    ['Per-key rate limiting', caps?.perKeyRateLimiting ? 'Implemented' : 'Unknown', 'Cloudflare rate-limit binding is required and missing binding fails closed.'],
    ['Origin validation', caps?.originValidation ? 'Implemented' : 'Unknown', 'HTTPS is required outside localhost development.'],
    ['Provider management', caps?.providerManagement ? 'Connected' : 'Not connected', 'Provider mutations remain disabled without an authoritative OmniRoute management API.'],
    ['Model management', caps?.modelManagement ? 'Connected' : 'Not connected', 'Model mutations remain disabled without an authoritative OmniRoute management API.'],
    ['Prompt firewall', caps?.promptFirewall ? 'Connected' : 'Not integrated', 'No local prompt firewall is simulated.'],
  ] as const;

  return <div className="flex flex-col gap-3 h-full w-full overflow-y-auto pr-1">
    <section className="card-3d-glass p-4 flex flex-wrap items-center gap-3"><div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center"><Server size={18}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-[14px] font-bold text-slate-900">Settings & Deployment Posture</h2><SourcePill label="Read-only posture"/></div><p className="text-[10.5px] text-slate-500 mt-0.5">Configuration visibility, truthful capability state, connectivity evidence, and browser-local admin access.</p></div><span className="text-[9.5px] font-mono text-slate-500">{caps?.environment ?? 'environment unknown'}</span></section>

    {runtimeWarning ? <section className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] text-amber-800"><div className="flex items-center gap-2"><CircleHelp size={14}/><strong>Runtime warning</strong></div><p className="mt-1">{runtimeWarning}</p></section> : null}

    <section className="card-3d-glass p-3"><WorkspaceTabs tabs={['General','Data','OmniRoute','Cloudflare','Advanced'].map((label)=>({id:label,label}))} active={tab} onChange={setTab}/></section>

    {tab==='General'?<div className="grid grid-cols-1 xl:grid-cols-3 gap-3">
      <section className="card-3d-glass p-4"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><KeyRound size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Admin Session Token</h3></div><p className="mt-2 text-[10px] text-slate-500">Optional browser-local break-glass token for app-level admin APIs. Empty grants nothing; there is no built-in default.</p><div className="flex gap-2 mt-3"><input type="password" value={tokenDraft} onChange={(e)=>setTokenDraft(e.target.value)} placeholder="admin token" className="min-w-0 flex-1 h-9 px-3 rounded-lg border border-slate-200 bg-white text-[11px] font-mono outline-none focus:border-blue-500"/><button onClick={saveToken} disabled={!tokenDraft.trim()} className="px-3 rounded-lg bg-blue-700 text-white text-[10px] font-bold disabled:opacity-40">Save</button><button onClick={clearToken} className="px-2 rounded-lg border border-slate-200 text-slate-500"><Trash2 size={13}/></button></div><div className="mt-2 text-[9.5px] text-slate-500">{tokenSaved?'Browser token setting updated.':tokenDraft?`${tokenDraft.length} characters entered; strength is not inferred.`:'No browser-local token configured.'}</div></section>
      <section className="card-3d-glass p-4 xl:col-span-2"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><Globe2 size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Observed Readiness</h3><span className="ml-auto text-[9px] text-slate-500">{data.readiness?.checkedAt?`Checked ${formatRelativeTime(data.readiness.checkedAt)}`:'No data'}</span></div><div className="mt-3 grid grid-cols-2 md:grid-cols-5 gap-2 text-[10px]">{[['Requests / 24h',data.readiness?.requestCount24h],['Errors / 24h',data.readiness?.errorCount24h],['Gateway keys',data.readiness?.gatewayKeys],['Admin keys',data.readiness?.adminKeys],['Inventory models',data.readiness?.modelCount]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-slate-50 border border-slate-200 p-2"><span className="text-slate-500">{label}</span><strong className="block">{value??'—'}</strong></div>)}</div><div className="mt-3 rounded-lg border border-slate-200 p-2.5 text-[10px] text-slate-600">{data.readiness?.issues?.length?data.readiness.issues.map((issue)=><div key={issue} className="flex gap-1.5 mb-1"><CircleHelp size={12} className="mt-0.5 text-amber-600"/><span>{issue}</span></div>):data.readiness?<div className="flex items-center gap-1.5 text-emerald-700"><CheckCircle2 size={12}/>No control-plane readiness issues reported.</div>:<div className="flex items-center gap-1.5"><CircleHelp size={12}/>Readiness data unavailable.</div>}</div></section>
    </div>:null}

    {tab==='Data'?<section className="card-3d-glass p-4"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><Database size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Data & Telemetry Sources</h3></div><div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-2"><PostureRow label="Request lifecycle" value="D1 edge telemetry" detail="Status, latency, path, correlation ID, authenticated key identity and requested model when safely parsed from the real request." ok/><PostureRow label="Provider/model inventory" value="Legacy read model" detail="Snapshot metadata only; not authoritative routing or health state."/><PostureRow label="Security events" value="D1 observed events" detail="Only stored events are shown; absence does not imply firewall coverage." ok/><PostureRow label="Usage / cost" value="Nullable observed fields" detail="Tokens and cost stay unknown until an authoritative upstream integration records them." ok/></div><div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-[9.5px] text-slate-500">Snapshot status: provider/model inventory can render from local/reference storage, but live health remains unavailable unless OmniRoute supplies it.</div></section>:null}

    {tab==='OmniRoute'?<div className="grid grid-cols-1 xl:grid-cols-3 gap-3">
      <section className="card-3d-glass p-4"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><PlugZap size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">OmniRoute Connectivity</h3><button onClick={()=>void data.refetch()} className="ml-auto inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2 py-1 text-[9px] font-bold text-blue-700"><RefreshCw size={10}/>Ping / refresh</button></div><div className="mt-3"><DetailGrid><DetailItem label="Configured" value={status?status.configured?'Yes':'No':'Unknown'}/><DetailItem label="Reachable" value={status?.reachable===true?'Yes':status?.reachable===false?'No':'Unknown'}/><DetailItem label="Origin host" value={status?.originHost??'—'} mono/><DetailItem label="Probe" value="/v1/models" mono/><DetailItem label="HTTP / latency" value={`${status?.httpStatus??'—'} / ${status?.latencyMs!=null?`${status.latencyMs} ms`:'—'}`}/><DetailItem label="Model IDs observed" value={status?.modelCount??'—'}/></DetailGrid><div className="mt-3 text-[9.5px] text-slate-500">{status?.error?`Probe result: ${status.error}`:status?`Checked ${formatRelativeTime(status.checkedAt)}`:'No probe data.'}</div></div></section>
      <section className="card-3d-glass p-4 xl:col-span-2"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><ShieldCheck size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Capability Matrix</h3></div><div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-2">{capabilityRows.map(([label,value,detail])=><PostureRow key={label} label={label} value={value} detail={detail} ok={value==='Implemented'||value==='Connected'}/>)}</div></section>
    </div>:null}

    {tab==='Cloudflare'?<section className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3"><div className="card-3d-glass p-4"><div className="flex items-center gap-2"><Cloud size={14} className="text-orange-500"/><h3 className="text-[12px] font-bold">Cloudflare</h3></div><div className="mt-3"><DetailGrid><DetailItem label="Environment" value={caps?.environment??'Unknown'}/><DetailItem label="Edge telemetry" value={caps?.requestTelemetry??'Unknown'}/><DetailItem label="Rate limiting" value={caps?.perKeyRateLimiting?'Configured capability':'Unknown'}/><DetailItem label="Origin validation" value={caps?.originValidation?'Implemented':'Unknown'}/></DetailGrid></div></div><div className="card-3d-glass p-4 md:col-span-1 xl:col-span-2"><h3 className="text-[12px] font-bold">Deployment bindings</h3><p className="mt-2 text-[9.5px] text-slate-500">Worker version, D1 database ID, Analytics Engine binding, Tunnel identity, colo, and custom-domain status are not exposed by the current runtime API. They remain Unknown rather than being inferred from the browser location.</p></div></section>:null}

    {tab==='Advanced'?<div className="space-y-3"><section className="card-3d-glass p-4"><div className="flex items-center gap-2"><Wrench size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Advanced diagnostics</h3></div><div className="mt-3"><DetailGrid><DetailItem label="Runtime metrics source" value={runtime?.source??'unavailable'}/><DetailItem label="Node runtime uptime" value={runtime?.uptimeSeconds!=null?`${Math.floor(runtime.uptimeSeconds/3600)}h ${Math.floor((runtime.uptimeSeconds%3600)/60)}m`:'Unknown'}/><DetailItem label="Heap used" value={runtime?.heapUsedMb!=null?`${runtime.heapUsedMb.toFixed(1)} MB`:'Unknown'}/><DetailItem label="RSS" value={runtime?.rssMb!=null?`${runtime.rssMb.toFixed(1)} MB`:'Unknown'}/></DetailGrid></div></section><BootstrapAdminCard/><div className="card-3d-glass p-3 text-[10px] text-slate-500 flex items-start gap-2"><Info size={13} className="text-blue-600 mt-0.5"/><span>Operational values are rendered only from observed telemetry or configured connectivity probes. Unknown values remain unknown; no provider-health simulation, local routing weights, synthetic cost, or synthetic traffic is generated.</span></div></div>:null}
  </div>;
};
