import React, { useMemo, useState } from 'react';
import { Activity, Boxes, Info, RefreshCw, Share2 } from 'lucide-react';
import { DashboardData, Provider } from '../types';
import { TopologyMap } from './TopologyMap';
import { MetricTile } from './PagePrimitives';
import { DetailGrid, DetailItem, InspectorDrawer, SourcePill } from './WorkspacePrimitives';
import { formatLatency, formatNumber } from '../utils/formatters';

export const TopologyView: React.FC<{ data: DashboardData }> = ({ data }) => {
  const [status, setStatus] = useState<'all' | 'healthy' | 'degraded' | 'offline'>('all');
  const [selected, setSelected] = useState<Provider | null>(null);
  const visibleProviders = useMemo(() => status === 'all' ? data.providers : data.providers.filter((provider) => provider.status.toLowerCase() === status), [data.providers, status]);
  const observedProviders = data.providers.filter((provider)=>(provider.requestsLast24h??0)>0).length;
  const liveHealth = data.providers.filter((provider)=>provider.healthSource==='omniroute').length;

  return <div className="flex flex-col h-full w-full gap-2.5 overflow-y-auto pr-1">
    <section className="card-3d-glass p-3 flex flex-wrap items-center justify-between gap-3 shrink-0"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center"><Share2 size={16}/></div><div><div className="flex items-center gap-2"><h2 className="text-[14px] font-bold text-slate-900">AI Topology Workspace</h2><SourcePill label="Read-only"/></div><p className="text-[10px] text-slate-500 mt-0.5">Observed edge telemetry and provider metadata. OmniRoute is the only routing authority.</p></div></div><div className="flex items-center gap-2"><select value={status} onChange={(event)=>setStatus(event.target.value as typeof status)} className="bg-white border border-slate-200 rounded-md px-2 py-1 text-[10px] text-slate-700"><option value="all">All provider states</option><option value="healthy">Healthy</option><option value="degraded">Degraded</option><option value="offline">Offline</option></select><SourcePill label={`Filter result · ${visibleProviders.length}`} tone="blue"/><button onClick={()=>data.refetch()} className="flex items-center gap-1.5 px-2.5 py-1 rounded-md border border-slate-200 bg-white text-blue-700 text-[10px] font-bold"><RefreshCw size={11} className={data.loading?'animate-spin':''}/>Refresh</button></div></section>

    <section className="grid grid-cols-2 xl:grid-cols-4 gap-2.5"><MetricTile icon={Boxes} label="Configured providers" value={formatNumber(data.providers.length)} note="Inventory metadata"/><MetricTile icon={Activity} label="Observed traffic" value={formatNumber(observedProviders)} note="Providers with request attribution"/><MetricTile label="Authoritative health" value={liveHealth?formatNumber(liveHealth):'Unavailable'} note="OmniRoute-reported only"/><MetricTile label="Filter result" value={`${visibleProviders.length}/${data.providers.length}`} note="Current provider-state filter"/></section>

    <div className="grid grid-cols-1 lg:grid-cols-12 gap-2.5 flex-1 min-h-[430px]">
      <div className="lg:col-span-9 min-h-[430px]"><TopologyMap data={data}/></div>
      <aside className="lg:col-span-3 card-3d-glass p-3.5 min-h-0 overflow-auto"><div className="flex items-center gap-2 pb-2 border-b border-slate-200"><Info size={14} className="text-blue-600"/><h3 className="text-[12px] font-bold">Topology inspector</h3></div><dl className="mt-3 grid gap-2 text-[10px]"><div className="flex justify-between"><dt className="text-slate-500">Routing authority</dt><dd className="font-bold">OmniRoute</dd></div><div className="flex justify-between"><dt className="text-slate-500">Observed requests</dt><dd className="font-mono font-bold">{data.topology?.nodes.router.totalRequestsLast24h ?? '—'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Configured providers</dt><dd className="font-mono font-bold">{data.providers.length}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Filter result</dt><dd className="font-mono font-bold">{visibleProviders.length}</dd></div></dl><div className="mt-4"><h4 className="text-[10px] font-bold text-slate-700 mb-2">Provider state</h4><div className="grid gap-1.5">{visibleProviders.map((provider)=><button key={provider.id} onClick={()=>setSelected(provider)} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-[9.5px] hover:bg-blue-50/30"><span className="flex min-w-0 items-center gap-2"><i className={`h-2 w-2 shrink-0 rounded-full ${provider.status==='Healthy'?'bg-emerald-500':provider.status==='Degraded'?'bg-amber-500':provider.status==='Offline'?'bg-rose-500':'bg-slate-300'}`}/><span className="font-semibold text-slate-800 truncate">{provider.name}</span></span><span className="text-slate-500">{provider.status||'Unknown'}</span></button>)}{!visibleProviders.length?<p className="text-[9.5px] text-slate-500">No provider metadata for this filter.</p>:null}</div></div><p className="mt-4 text-[9px] leading-relaxed text-slate-500">Provider selection, retry and fallback are intentionally not simulated here. Connect an authoritative OmniRoute management/telemetry API before enabling control actions.</p></aside>
    </div>

    <InspectorDrawer open={Boolean(selected)} onClose={()=>setSelected(null)} title="Topology provider detail" subtitle={selected?.id}>
      {selected?<div className="space-y-3"><DetailGrid><DetailItem label="Provider" value={selected.name}/><DetailItem label="State" value={selected.status}/><DetailItem label="Observed requests" value={(selected.requestsLast24h??0)>0?formatNumber(selected.requestsLast24h??0):'Not observed'}/><DetailItem label="Observed traffic share" value={(selected.trafficSharePct??0)>0?`${selected.trafficSharePct?.toFixed(1)}%`:'Not observed'}/><DetailItem label="Live latency" value={selected.healthSource==='omniroute'?formatLatency(selected.latencyMs):'Not observed'}/><DetailItem label="Health authority" value={selected.healthSource==='omniroute'?'OmniRoute':'Unavailable'}/></DetailGrid><div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-[9px] text-blue-900">This inspector is descriptive only; it cannot alter provider selection or route traffic.</div></div>:null}
    </InspectorDrawer>
  </div>;
};
